# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-01 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0002_auto_20170302_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
            ],
            options={
                'verbose_name': 'result_photo',
                'verbose_name_plural': 'result_photos',
            },
        ),
    ]
