# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-02 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_resultphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultphoto',
            name='index',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
